# example stages
# see https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml
stages:
  1-stage:
    cmd: Rscript stages/01-stage.R
    deps:
      - stages/01-stage.R
    outs:
      - data/mtcars.parquet