stages:
  crawl:
    cmd: clj -X biobricks.echemportal/crawl-substances && mv target/echemportal data/crawl
    deps:
      - data/echemportal-version
    outs:
      - data/crawl
  to-parquet:
    cmd: clj -X biobricks.echemportal/crawl-to-parquet '{:crawl-results "data/crawl" :output "data/echemportal.parquet"}'
    deps:
      - data/crawl
    outs:
      - data/echemportal.parquet
