stages:
  crawl:
    cmd: python3 stages/01_crawl.py
    deps:
      - stages/01_crawl.py
      - data/echemportal-version
    outs:
      - download/crawl
  build:
    cmd: python3 stages/02_build.py
    deps:
      - stages/02_build.py
      - download/crawl
    outs:
      - brick
