# example stages
# see https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml
stages:
  echemportal:
    cmd: cp ../brick-builder/target/echemportal.parquet data
    outs:
      - data/echemportal.parquet
